# Site settings
title: 孤岛上的野鬼
email: "shenglaodayu@hotmail.com"
description: "天地与我为一，万物与我共生"
baseurl: ""
url: "http://sishugang.github.io"
permalink: /:year/:title


# Social account
weibo:    tixiaoyy
github:   sishugang
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
