permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true
encoding:utf-8

kramdown:
  input: GFM

# 作者信息
author: 
  name: 司舒刚
  email: shenglaodayu@gmail.com
  link: http://sishugang.github.io
  weibo: http://weibo.com/yansu0711
  github: http://github.com/sishugang

# 站点信息
title: 司舒刚的博客 
description: 司舒刚的博客
url: http://sishugang.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: sishugang.github.io

# disqus 设置
disqus:
  shortname: sishugang-zh
